import type {
  BuilderLayoutKey,
  BuilderTemplate,
  LayoutBlockKind,
  SectionKind,
} from "@/components/dashboard/builderTypes";

export const sectionLabels: Record<SectionKind, string> = {
  hero: "Hero",
  productArchive: "Product Archive",
  recentlyViewed: "Recently Viewed",
  filters: "Top Category Filters",
  promo: "Promo Strip",
  slider: "Swiper / Carousel",
  badgeGrid: "Badge Grid",
  contentLayout: "Section Layout",
  embed: "Embed / Code",
  scrollPinnedDemo: "Pinned Story",
};

export const layoutBlockLabels: Record<LayoutBlockKind, string> = {
  hero: "Hero",
  button: "Button",
  grid: "Grid",
  heading: "Heading",
  image: "Image",
  panel: "Panel",
  accordion: "Accordion",
  table: "Table",
  gallery: "Gallery",
  text: "Text",
  slider: "Swiper / Carousel",
  panelSlider: "Panel Slider",
  scrollPinnedDemo: "Scroll Pinned Demo",
  embed: "HTML",
  fluentForm: "Fluent Form",
  badgeGrid: "Badges",
  icon: "Icon",
  list: "List",
  menu: "Menu",
  headerUtility: "Utility Action",
  headerSearch: "Search",
  headerWishlist: "Wishlist",
  headerCart: "Cart",
  headerAccount: "Account",
  headerTheme: "Theme Switcher",
  headerCategories: "Category Menu",
  headerLanguage: "Language Switcher",
  datePicker: "Date Picker",
  products: "Products",
  categoryFilters: "Category Filters",
  breadcrumbs: "Breadcrumbs",
  productHero: "Product Hero",
  productInfoStack: "Product Info Stack",
  productPurchasePanel: "Purchase Panel",
  productSpecsPanel: "Specs Panel",
  productGallery: "Product Gallery",
  productTitle: "Product Title",
  productPrice: "Product Price",
  productAddToCart: "Add To Cart",
  productAttributes: "Product Details",
  productDescription: "Description",
  cartContent: "Cart Content",
  checkoutContent: "Checkout Content",
  accountContent: "My Account Content",
  divider: "Divider",
  alert: "Alert",
};

export const baseLayoutBlockKinds: LayoutBlockKind[] = [
  "hero",
  "button",
  "grid",
  "heading",
  "image",
  "panel",
  "table",
  "text",
  "slider",
  "panelSlider",
  "scrollPinnedDemo",
  "fluentForm",
  "embed",
  "badgeGrid",
  "icon",
  "list",
  "datePicker",
  "products",
  "categoryFilters",
  "breadcrumbs",
  "cartContent",
  "checkoutContent",
  "accountContent",
  "divider",
  "accordion",
  "alert",
  "gallery",
];

export const productLayoutBlockKinds: LayoutBlockKind[] = [
  "productHero",
  "productInfoStack",
  "productPurchasePanel",
  "productSpecsPanel",
  "productGallery",
  "productTitle",
  "productPrice",
  "productAddToCart",
  "productAttributes",
  "productDescription",
];

export const layoutBlockDescriptions: Record<LayoutBlockKind, string> = {
  hero: "Large intro with eyebrow, title, copy, and button.",
  button: "A standalone call-to-action button.",
  grid: "Configurable static or dynamic card grid.",
  heading: "A standalone heading with level and alignment options.",
  image: "Simple image block with optional caption metadata.",
  panel: "Image, eyebrow, title, copy, and button in one content block.",
  accordion: "Accessible disclosure list with editable titles and content.",
  text: "Static copy, button, and small editorial content.",
  gallery: "Interactive image gallery with lightbox, overlay, and filter navigation.",
  table: "Editable data table with headers and styled rows.",
  slider: "Swiper carousel with editable slides and images.",
  panelSlider: "Panel cards with shared Grid settings, shown in a responsive Swiper slider.",
  scrollPinnedDemo: "An elegant storytelling block with scroll pinning.",
  embed: "Forms, chat widgets, maps, or trusted HTML.",
  fluentForm: "Render a Fluent Forms form from WordPress by form ID.",
  badgeGrid: "Compact promises, services, or feature badges.",
  icon: "Decorative icon with optional label and text.",
  list: "Clean bullet or checklist content.",
  menu: "Website navigation rendered from a selected menu source.",
  headerUtility: "An existing Header utility such as cart, account, search, or theme.",
  headerSearch: "The existing Header search action.",
  headerWishlist: "The existing Header wishlist action.",
  headerCart: "The existing Header cart action.",
  headerAccount: "The existing Header account action.",
  headerTheme: "The existing Header theme switcher.",
  headerCategories: "The existing category burger and dropdown.",
  headerLanguage: "Switch between the website's enabled content languages.",
  datePicker: "Native date input for bookings, forms, or delivery dates.",
  products: "Dynamic WooCommerce product grid or carousel.",
  categoryFilters: "Dynamic WooCommerce category pills.",
  breadcrumbs: "Dynamic page or product breadcrumbs.",
  productHero: "Premium product intro using live product fields.",
  productInfoStack: "Title, price, description, and purchase action.",
  productPurchasePanel: "Focused buy box with price, cart, and details.",
  productSpecsPanel: "Clean dynamic attribute/specification panel.",
  productGallery: "Dynamic current product gallery.",
  productTitle: "Dynamic current product title.",
  productPrice: "Dynamic current product price.",
  productAddToCart: "Dynamic WooCommerce add-to-cart action.",
  productAttributes: "Dynamic current product attributes.",
  productDescription: "Dynamic current product description.",
  cartContent: "Live cart page content slot.",
  checkoutContent: "Live checkout page content slot.",
  accountContent: "Live my-account page content slot.",
  divider: "UIkit horizontal line or icon divider.",
  alert: "UIkit notification or alert callout box.",
};

export const layoutBlockGroups: {
  id: string;
  label: string;
  kinds: LayoutBlockKind[];
}[] = [
  {
    id: "basic",
    label: "Basic",
    kinds: [
      "hero",
      "heading",
      "text",
      "button",
      "image",
      "panel",
      "divider",
      "alert",
      "icon",
      "list",
    ],
  },
  {
    id: "multiple-items",
    label: "Multiple Items",
    kinds: ["accordion", "grid", "gallery", "table", "slider", "panelSlider", "badgeGrid", "categoryFilters"],
  },
  {
    id: "commerce",
    label: "Commerce",
    kinds: [
      "products",
      "productHero",
      "productInfoStack",
      "productPurchasePanel",
      "productSpecsPanel",
      "productGallery",
      "productTitle",
      "productPrice",
      "productAddToCart",
      "productAttributes",
      "productDescription",
      "cartContent",
      "checkoutContent",
      "accountContent",
    ],
  },
  {
    id: "forms",
    label: "Forms",
    kinds: ["fluentForm", "datePicker"],
  },
  {
    id: "system",
    label: "System",
    kinds: ["breadcrumbs", "menu", "headerUtility", "headerSearch", "headerWishlist", "headerCart", "headerAccount", "headerTheme", "headerCategories", "headerLanguage"],
  },
  {
    id: "advanced",
    label: "Advanced",
    kinds: ["embed", "scrollPinnedDemo"],
  },
];

export const basePageLabels: Record<string, string> = {
  home: "Home",
  shop: "Shop",
  client: "Client Page",
  "page:cart": "Cart",
  "page:checkout": "Checkout",
  "page:my-account": "My Account",
};

export const templateLabels: Record<BuilderTemplate, string> = {
  "product-single": "Single Product",
  "product-category": "Product Category",
  "product-category-specific": "Specific Category",
  "search-results": "Search Results",
};

export const templateDescriptions: Record<BuilderTemplate, string> = {
  "product-single": "Default layout for every product detail page.",
  "product-category": "Default layout for product category archive pages.",
  "product-category-specific":
    "Override layout for one chosen product category.",
  "search-results": "Default layout for search result pages.",
};

export const layoutLabels: Partial<Record<BuilderLayoutKey, string>> = {
  header: "Header",
  footer: "Footer",
  ...basePageLabels,
  ...templateLabels,
};

export const builderLayoutKeys = new Set<BuilderLayoutKey>([
  "header",
  "footer",
  "home",
  "shop",
  "client",
  "page:cart",
  "page:checkout",
  "page:my-account",
  "product-single",
  "product-category",
  "product-category-specific",
  "search-results",
]);

export function getLayoutBlockKindsForState() {
  return [...baseLayoutBlockKinds, ...productLayoutBlockKinds];
}
