import type {
  BuilderDesign,
  BuilderShellSettings,
} from "@/components/dashboard/builderTypes";

export type GlobalStylePreset = {
  id: string;
  name: string;
  description: string;
  palette: string[];
  previewImage: string;
  design: Partial<BuilderDesign>;
  shellSettings: Partial<BuilderShellSettings>;
};

function presetPreviewSvg({
  name,
  background,
  surface,
  text,
  muted,
  accent,
}: {
  name: string;
  background: string;
  surface: string;
  text: string;
  muted: string;
  accent: string;
}) {
  const svg = `
    <svg xmlns="http://www.w3.org/2000/svg" width="560" height="340" viewBox="0 0 560 340" role="img" aria-label="${name} preview">
      <rect width="560" height="340" rx="26" fill="${background}"/>
      <rect x="34" y="30" width="492" height="46" rx="23" fill="${surface}" stroke="${muted}" stroke-opacity=".26"/>
      <circle cx="61" cy="53" r="11" fill="${accent}"/>
      <rect x="88" y="47" width="92" height="12" rx="6" fill="${text}" opacity=".92"/>
      <rect x="324" y="47" width="46" height="10" rx="5" fill="${muted}" opacity=".58"/>
      <rect x="388" y="47" width="46" height="10" rx="5" fill="${muted}" opacity=".58"/>
      <rect x="452" y="42" width="52" height="20" rx="10" fill="${accent}"/>
      <rect x="48" y="112" width="245" height="38" rx="8" fill="${text}" opacity=".96"/>
      <rect x="48" y="166" width="194" height="13" rx="7" fill="${muted}" opacity=".72"/>
      <rect x="48" y="188" width="228" height="13" rx="7" fill="${muted}" opacity=".48"/>
      <rect x="48" y="232" width="114" height="38" rx="19" fill="${accent}"/>
      <rect x="320" y="112" width="176" height="178" rx="22" fill="${surface}" stroke="${muted}" stroke-opacity=".22"/>
      <rect x="346" y="138" width="124" height="92" rx="18" fill="${accent}" opacity=".18"/>
      <rect x="346" y="248" width="94" height="12" rx="6" fill="${text}" opacity=".86"/>
      <rect x="346" y="270" width="116" height="10" rx="5" fill="${muted}" opacity=".56"/>
    </svg>
  `;

  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}

const iconOrder: BuilderShellSettings["headerIconOrder"] = [
  "wishlist",
  "cart",
  "account",
  "theme",
  "search",
];

export const GLOBAL_STYLE_PRESETS: GlobalStylePreset[] = [
  {
    id: "minimal",
    name: "Minimal",
    description: "Precise whitespace, monochrome controls, and quiet cards.",
    palette: ["#ffffff", "#111111", "#6b7280", "#f3f4f6"],
    previewImage: presetPreviewSvg({
      name: "Minimal",
      background: "#ffffff",
      surface: "#f7f7f7",
      text: "#111111",
      muted: "#6b7280",
      accent: "#111111",
    }),
    design: {
      preset: undefined,
      colorScheme: "light",
      pageBackground: "#ffffff",
      textColor: "#111111",
      mutedTextColor: "#6b7280",
      accentColor: "#111111",
      surfaceColor: "#f7f7f7",
      buttonBackground: "#111111",
      buttonTextColor: "#ffffff",
      radius: "8px",
      sectionMaxWidth: "1540px",
      sectionGutter: "44px",
      headingFontFamily: "inherit",
      headingSize: "clamp(38px, 6vw, 96px)",
      headingWeight: "700",
      headingLineHeight: "1",
      headingColor: "#111111",
      cardBg: "#ffffff",
      cardRadius: "8px",
      cardBorder: "rgba(17, 17, 17, 0.1)",
      cardShadow: "0 1px 2px rgba(17, 24, 39, 0.06)",
      cardShadowHover: "0 12px 32px rgba(17, 24, 39, 0.1)",
      cardImageBg: "#f7f7f7",
      cardImagePadding: "clamp(18px, 2vw, 30px)",
    },
    shellSettings: {
      storefrontPreset: "minimal",
      primaryColor: "#111111",
      accentColor: "#111111",
      headerVisible: true,
      topToolbarVisible: false,
      headerBackgroundMode: "default",
      headerTextMode: "auto",
      headerLayout: "simple",
      headerBrandMode: "logo",
      headerIconVariant: "muted",
      headerIconOrder: iconOrder,
      headerActiveIndicator: "underline",
      sectionPaddingTop: "large",
      sectionPaddingBottom: "large",
      sectionMarginTop: "none",
      sectionMarginBottom: "none",
      rowPaddingTop: "sm",
      rowPaddingBottom: "sm",
      rowMarginTop: "none",
      rowMarginBottom: "none",
      rowGap: "md",
      elementPaddingTop: "sm",
      elementPaddingRight: "sm",
      elementPaddingBottom: "sm",
      elementPaddingLeft: "sm",
      elementMarginTop: "none",
      elementMarginRight: "none",
      elementMarginBottom: "none",
      elementMarginLeft: "none",
      productCardRadius: "8px",
      productCardBg: "#ffffff",
      productCardShadow: "0 1px 2px rgba(17, 24, 39, 0.06)",
      productCardShadowHover: "0 12px 32px rgba(17, 24, 39, 0.1)",
      productCardMinHeight: "0px",
      productCardMaxWidth: "100%",
      productImageWidth: "100%",
      productImageHeight: "260px",
      productImageMaxWidth: "100%",
      productImageMaxHeight: "100%",
      productImageAspectRatio: "auto",
      productImageNoPadding: false,
      productImagePadding: "clamp(18px, 2vw, 30px)",
      productImageObjectFit: "contain",
      buttonBg: "#111111",
      buttonTextColor: "#ffffff",
      buttonBorderRadius: "999px",
      buttonBorderWidth: "1px",
      buttonBorderColor: "#111111",
      buttonPaddingY: "11px",
      buttonPaddingX: "18px",
      buttonFontWeight: "720",
      buttonLetterSpacing: "0px",
      buttonHoverBg: "#2f2f2f",
      buttonHoverTextColor: "#ffffff",
      buttonHoverBorderColor: "#2f2f2f",
      buttonHoverEffect: "lift",
    },
  },
  {
    id: "modern-business",
    name: "Modern Business",
    description: "Confident blue accents, crisp cards, and structured spacing.",
    palette: ["#f5f8ff", "#102033", "#2563eb", "#ffffff"],
    previewImage: presetPreviewSvg({
      name: "Modern Business",
      background: "#f5f8ff",
      surface: "#ffffff",
      text: "#102033",
      muted: "#64748b",
      accent: "#2563eb",
    }),
    design: {
      preset: undefined,
      colorScheme: "light",
      pageBackground: "#f5f8ff",
      textColor: "#102033",
      mutedTextColor: "#64748b",
      accentColor: "#2563eb",
      surfaceColor: "#ffffff",
      buttonBackground: "#2563eb",
      buttonTextColor: "#ffffff",
      radius: "12px",
      sectionMaxWidth: "1620px",
      sectionGutter: "48px",
      headingFontFamily: "inherit",
      headingSize: "clamp(40px, 7vw, 112px)",
      headingWeight: "760",
      headingLineHeight: "0.96",
      headingColor: "#102033",
      cardBg: "#ffffff",
      cardRadius: "12px",
      cardBorder: "rgba(37, 99, 235, 0.12)",
      cardShadow: "0 12px 34px rgba(15, 23, 42, 0.08)",
      cardShadowHover: "0 20px 48px rgba(37, 99, 235, 0.16)",
      cardImageBg: "#eef4ff",
      cardImagePadding: "clamp(20px, 2.2vw, 34px)",
    },
    shellSettings: {
      storefrontPreset: "elevated",
      primaryColor: "#2563eb",
      accentColor: "#2563eb",
      headerVisible: true,
      topToolbarVisible: true,
      headerBackgroundMode: "glass",
      headerTextMode: "auto",
      headerLayout: "pill",
      headerBrandMode: "both",
      headerIconVariant: "ghost",
      headerIconOrder: ["search", "wishlist", "cart", "account", "theme"],
      headerActiveIndicator: "underline",
      sectionPaddingTop: "large",
      sectionPaddingBottom: "large",
      sectionMarginTop: "none",
      sectionMarginBottom: "none",
      rowPaddingTop: "md",
      rowPaddingBottom: "md",
      rowMarginTop: "none",
      rowMarginBottom: "none",
      rowGap: "lg",
      elementPaddingTop: "sm",
      elementPaddingRight: "sm",
      elementPaddingBottom: "sm",
      elementPaddingLeft: "sm",
      elementMarginTop: "none",
      elementMarginRight: "none",
      elementMarginBottom: "none",
      elementMarginLeft: "none",
      productCardRadius: "12px",
      productCardBg: "#ffffff",
      productCardShadow: "0 12px 34px rgba(15, 23, 42, 0.08)",
      productCardShadowHover: "0 20px 48px rgba(37, 99, 235, 0.16)",
      productCardMinHeight: "0px",
      productCardMaxWidth: "100%",
      productImageWidth: "100%",
      productImageHeight: "270px",
      productImageMaxWidth: "100%",
      productImageMaxHeight: "100%",
      productImageAspectRatio: "auto",
      productImageNoPadding: false,
      productImagePadding: "clamp(20px, 2.2vw, 34px)",
      productImageObjectFit: "contain",
      buttonBg: "#2563eb",
      buttonTextColor: "#ffffff",
      buttonBorderRadius: "12px",
      buttonBorderWidth: "1px",
      buttonBorderColor: "#2563eb",
      buttonPaddingY: "12px",
      buttonPaddingX: "20px",
      buttonFontWeight: "760",
      buttonLetterSpacing: "0px",
      buttonHoverBg: "#1d4ed8",
      buttonHoverTextColor: "#ffffff",
      buttonHoverBorderColor: "#1d4ed8",
      buttonHoverEffect: "lift",
    },
  },
  {
    id: "elegant",
    name: "Elegant",
    description: "Editorial typography, warm surfaces, and refined borders.",
    palette: ["#fbf8f3", "#2a211c", "#9b5c3d", "#efe7dd"],
    previewImage: presetPreviewSvg({
      name: "Elegant",
      background: "#fbf8f3",
      surface: "#efe7dd",
      text: "#2a211c",
      muted: "#7c6f66",
      accent: "#9b5c3d",
    }),
    design: {
      preset: "editorial",
      headingColor: "#2a211c",
    },
    shellSettings: {
      storefrontPreset: "boutique",
      primaryColor: "#2a211c",
      accentColor: "#9b5c3d",
      headerVisible: true,
      topToolbarVisible: true,
      headerBackgroundMode: "default",
      headerTextMode: "auto",
      headerLayout: "two-row",
      headerBrandMode: "both",
      headerIconVariant: "muted",
      headerIconOrder: iconOrder,
      headerActiveIndicator: "underline",
      sectionPaddingTop: "large",
      sectionPaddingBottom: "large",
      rowPaddingTop: "md",
      rowPaddingBottom: "md",
      rowGap: "lg",
      productCardRadius: "4px",
      productCardBg: "#ffffff",
      productCardShadow: "0 8px 24px rgba(42, 33, 28, 0.06)",
      productCardShadowHover: "0 16px 42px rgba(42, 33, 28, 0.12)",
      productImagePadding: "clamp(18px, 2vw, 32px)",
      productImageObjectFit: "contain",
      buttonBg: "#2a211c",
      buttonTextColor: "#ffffff",
      buttonBorderRadius: "4px",
      buttonBorderWidth: "1px",
      buttonBorderColor: "#2a211c",
      buttonPaddingY: "12px",
      buttonPaddingX: "20px",
      buttonFontWeight: "700",
      buttonLetterSpacing: "0px",
      buttonHoverBg: "#9b5c3d",
      buttonHoverTextColor: "#ffffff",
      buttonHoverBorderColor: "#9b5c3d",
      buttonHoverEffect: "lift",
    },
  },
  {
    id: "creative",
    name: "Creative",
    description: "Energetic color, softer forms, and expressive hierarchy.",
    palette: ["#fff7ed", "#231942", "#f97316", "#fef3c7"],
    previewImage: presetPreviewSvg({
      name: "Creative",
      background: "#fff7ed",
      surface: "#fef3c7",
      text: "#231942",
      muted: "#7c5a40",
      accent: "#f97316",
    }),
    design: {
      preset: undefined,
      colorScheme: "light",
      pageBackground: "#fff7ed",
      textColor: "#231942",
      mutedTextColor: "#7c5a40",
      accentColor: "#f97316",
      surfaceColor: "#fef3c7",
      buttonBackground: "#f97316",
      buttonTextColor: "#ffffff",
      radius: "18px",
      sectionMaxWidth: "1580px",
      sectionGutter: "46px",
      headingFontFamily: "inherit",
      headingSize: "clamp(44px, 8vw, 122px)",
      headingWeight: "760",
      headingLineHeight: "0.94",
      headingColor: "#231942",
      cardBg: "#ffffff",
      cardRadius: "18px",
      cardBorder: "rgba(249, 115, 22, 0.16)",
      cardShadow: "0 14px 36px rgba(124, 58, 18, 0.1)",
      cardShadowHover: "0 24px 58px rgba(249, 115, 22, 0.18)",
      cardImageBg: "#fef3c7",
      cardImagePadding: "clamp(20px, 2.4vw, 38px)",
    },
    shellSettings: {
      storefrontPreset: "soft",
      primaryColor: "#231942",
      accentColor: "#f97316",
      headerVisible: true,
      topToolbarVisible: false,
      headerBackgroundMode: "accent",
      headerTextMode: "light",
      headerLayout: "hero",
      headerBrandMode: "both",
      headerIconVariant: "solid",
      headerIconOrder: iconOrder,
      headerActiveIndicator: "underline",
      sectionPaddingTop: "large",
      sectionPaddingBottom: "large",
      rowPaddingTop: "md",
      rowPaddingBottom: "md",
      rowGap: "lg",
      productCardRadius: "18px",
      productCardBg: "#ffffff",
      productCardShadow: "0 14px 36px rgba(124, 58, 18, 0.1)",
      productCardShadowHover: "0 24px 58px rgba(249, 115, 22, 0.18)",
      productImagePadding: "clamp(20px, 2.4vw, 38px)",
      productImageObjectFit: "contain",
      buttonBg: "#f97316",
      buttonTextColor: "#ffffff",
      buttonBorderRadius: "999px",
      buttonBorderWidth: "1px",
      buttonBorderColor: "#f97316",
      buttonPaddingY: "12px",
      buttonPaddingX: "22px",
      buttonFontWeight: "780",
      buttonLetterSpacing: "0px",
      buttonHoverBg: "#ea580c",
      buttonHoverTextColor: "#ffffff",
      buttonHoverBorderColor: "#ea580c",
      buttonHoverEffect: "grow",
    },
  },
  {
    id: "dark",
    name: "Dark",
    description: "Immersive dark surfaces, neon accent, and high contrast.",
    palette: ["#101010", "#f7f7f1", "#d7ff63", "#24241f"],
    previewImage: presetPreviewSvg({
      name: "Dark",
      background: "#101010",
      surface: "#24241f",
      text: "#f7f7f1",
      muted: "#8f9188",
      accent: "#d7ff63",
    }),
    design: {
      preset: "contrast",
      headingColor: "#f7f7f1",
    },
    shellSettings: {
      storefrontPreset: "elevated",
      primaryColor: "#d7ff63",
      accentColor: "#d7ff63",
      headerVisible: true,
      topToolbarVisible: true,
      headerBackgroundMode: "glass",
      headerTextMode: "light",
      headerLayout: "pill",
      headerBrandMode: "both",
      headerIconVariant: "ghost",
      headerIconOrder: ["search", "wishlist", "cart", "account", "theme"],
      headerActiveIndicator: "underline",
      sectionPaddingTop: "large",
      sectionPaddingBottom: "large",
      rowPaddingTop: "md",
      rowPaddingBottom: "md",
      rowGap: "lg",
      productCardRadius: "10px",
      productCardBg: "#24241f",
      productCardShadow: "0 16px 40px rgba(0, 0, 0, 0.3)",
      productCardShadowHover: "0 22px 54px rgba(0, 0, 0, 0.42)",
      productImagePadding: "clamp(22px, 2.4vw, 36px)",
      productImageObjectFit: "contain",
      buttonBg: "#d7ff63",
      buttonTextColor: "#101010",
      buttonBorderRadius: "999px",
      buttonBorderWidth: "1px",
      buttonBorderColor: "#d7ff63",
      buttonPaddingY: "11px",
      buttonPaddingX: "20px",
      buttonFontWeight: "780",
      buttonLetterSpacing: "0px",
      buttonHoverBg: "#f1ffad",
      buttonHoverTextColor: "#101010",
      buttonHoverBorderColor: "#f1ffad",
      buttonHoverEffect: "lift",
    },
  },
  {
    id: "startup",
    name: "Startup",
    description: "Bright SaaS polish with rounded cards and punchy CTAs.",
    palette: ["#f8fbff", "#0f172a", "#14b8a6", "#e0f2fe"],
    previewImage: presetPreviewSvg({
      name: "Startup",
      background: "#f8fbff",
      surface: "#e0f2fe",
      text: "#0f172a",
      muted: "#64748b",
      accent: "#14b8a6",
    }),
    design: {
      preset: undefined,
      colorScheme: "light",
      pageBackground: "#f8fbff",
      textColor: "#0f172a",
      mutedTextColor: "#64748b",
      accentColor: "#14b8a6",
      surfaceColor: "#e0f2fe",
      buttonBackground: "#14b8a6",
      buttonTextColor: "#ffffff",
      radius: "16px",
      sectionMaxWidth: "1640px",
      sectionGutter: "48px",
      headingFontFamily: "inherit",
      headingSize: "clamp(42px, 7vw, 118px)",
      headingWeight: "780",
      headingLineHeight: "0.94",
      headingColor: "#0f172a",
      cardBg: "#ffffff",
      cardRadius: "16px",
      cardBorder: "rgba(20, 184, 166, 0.12)",
      cardShadow: "0 16px 42px rgba(15, 23, 42, 0.08)",
      cardShadowHover: "0 26px 64px rgba(20, 184, 166, 0.18)",
      cardImageBg: "#e0f2fe",
      cardImagePadding: "clamp(20px, 2.4vw, 38px)",
    },
    shellSettings: {
      storefrontPreset: "elevated",
      primaryColor: "#14b8a6",
      accentColor: "#14b8a6",
      headerVisible: true,
      topToolbarVisible: false,
      headerBackgroundMode: "glass",
      headerTextMode: "auto",
      headerLayout: "pill",
      headerBrandMode: "both",
      headerIconVariant: "ghost",
      headerIconOrder: ["search", "wishlist", "cart", "account", "theme"],
      headerActiveIndicator: "underline",
      sectionPaddingTop: "large",
      sectionPaddingBottom: "large",
      rowPaddingTop: "md",
      rowPaddingBottom: "md",
      rowGap: "lg",
      productCardRadius: "16px",
      productCardBg: "#ffffff",
      productCardShadow: "0 16px 42px rgba(15, 23, 42, 0.08)",
      productCardShadowHover: "0 26px 64px rgba(20, 184, 166, 0.18)",
      productImagePadding: "clamp(20px, 2.4vw, 38px)",
      productImageObjectFit: "contain",
      buttonBg: "#14b8a6",
      buttonTextColor: "#ffffff",
      buttonBorderRadius: "12px",
      buttonBorderWidth: "1px",
      buttonBorderColor: "#14b8a6",
      buttonPaddingY: "12px",
      buttonPaddingX: "20px",
      buttonFontWeight: "780",
      buttonLetterSpacing: "0px",
      buttonHoverBg: "#0f766e",
      buttonHoverTextColor: "#ffffff",
      buttonHoverBorderColor: "#0f766e",
      buttonHoverEffect: "lift",
    },
  },
  {
    id: "luxury",
    name: "Luxury",
    description: "Deep contrast, champagne accents, and refined sharp edges.",
    palette: ["#11100e", "#f7efe2", "#c7a56b", "#211d18"],
    previewImage: presetPreviewSvg({
      name: "Luxury",
      background: "#11100e",
      surface: "#211d18",
      text: "#f7efe2",
      muted: "#a19585",
      accent: "#c7a56b",
    }),
    design: {
      preset: undefined,
      colorScheme: "dark",
      pageBackground: "#11100e",
      textColor: "#f7efe2",
      mutedTextColor: "#a19585",
      accentColor: "#c7a56b",
      surfaceColor: "#211d18",
      buttonBackground: "#c7a56b",
      buttonTextColor: "#11100e",
      radius: "2px",
      sectionMaxWidth: "1560px",
      sectionGutter: "56px",
      headingFontFamily: "Georgia, serif",
      headingSize: "clamp(42px, 8vw, 128px)",
      headingWeight: "700",
      headingLineHeight: "0.94",
      headingColor: "#f7efe2",
      cardBg: "#211d18",
      cardRadius: "2px",
      cardBorder: "rgba(199, 165, 107, 0.2)",
      cardShadow: "0 18px 48px rgba(0, 0, 0, 0.35)",
      cardShadowHover: "0 28px 70px rgba(0, 0, 0, 0.5)",
      cardImageBg: "#17130f",
      cardImagePadding: "clamp(22px, 2.4vw, 36px)",
    },
    shellSettings: {
      storefrontPreset: "boutique",
      primaryColor: "#c7a56b",
      accentColor: "#c7a56b",
      headerVisible: true,
      topToolbarVisible: true,
      headerBackgroundMode: "none",
      headerTextMode: "light",
      headerLayout: "simple",
      headerBrandMode: "both",
      headerIconVariant: "icon",
      headerIconOrder: iconOrder,
      headerActiveIndicator: "underline",
      sectionPaddingTop: "large",
      sectionPaddingBottom: "large",
      rowPaddingTop: "md",
      rowPaddingBottom: "md",
      rowGap: "lg",
      productCardRadius: "2px",
      productCardBg: "#211d18",
      productCardShadow: "0 18px 48px rgba(0, 0, 0, 0.35)",
      productCardShadowHover: "0 28px 70px rgba(0, 0, 0, 0.5)",
      productImagePadding: "clamp(22px, 2.4vw, 36px)",
      productImageObjectFit: "contain",
      buttonBg: "#c7a56b",
      buttonTextColor: "#11100e",
      buttonBorderRadius: "2px",
      buttonBorderWidth: "1px",
      buttonBorderColor: "#c7a56b",
      buttonPaddingY: "12px",
      buttonPaddingX: "22px",
      buttonFontWeight: "760",
      buttonLetterSpacing: "0px",
      buttonHoverBg: "#f7efe2",
      buttonHoverTextColor: "#11100e",
      buttonHoverBorderColor: "#f7efe2",
      buttonHoverEffect: "lift",
    },
  },
  {
    id: "shop",
    name: "Shop",
    description: "Conversion-focused storefront styling with clear product cards.",
    palette: ["#f7f7f4", "#111111", "#a4be7b", "#ffffff"],
    previewImage: presetPreviewSvg({
      name: "Shop",
      background: "#f7f7f4",
      surface: "#ffffff",
      text: "#111111",
      muted: "#5f5f58",
      accent: "#a4be7b",
    }),
    design: {
      preset: "princity",
      headingColor: "#111111",
    },
    shellSettings: {
      storefrontPreset: "princity",
      primaryColor: "#111111",
      accentColor: "#a4be7b",
      headerVisible: true,
      topToolbarVisible: true,
      headerBackgroundMode: "default",
      headerTextMode: "auto",
      headerLayout: "princity",
      headerBrandMode: "brand",
      headerIconVariant: "muted",
      headerIconOrder: iconOrder,
      headerActiveIndicator: "princity",
      sectionPaddingTop: "medium",
      sectionPaddingBottom: "medium",
      sectionMarginTop: "none",
      sectionMarginBottom: "none",
      rowPaddingTop: "md",
      rowPaddingBottom: "md",
      rowMarginTop: "none",
      rowMarginBottom: "none",
      rowGap: "lg",
      elementPaddingTop: "sm",
      elementPaddingRight: "sm",
      elementPaddingBottom: "sm",
      elementPaddingLeft: "sm",
      elementMarginTop: "none",
      elementMarginRight: "none",
      elementMarginBottom: "none",
      elementMarginLeft: "none",
      productCardRadius: "10px",
      productCardBg: "#ffffff",
      productCardShadow: "0 0 0 rgba(15, 23, 42, 0)",
      productCardShadowHover: "0 18px 40px rgba(15, 23, 42, 0.14)",
      productCardMinHeight: "0px",
      productCardMaxWidth: "100%",
      productImageWidth: "100%",
      productImageHeight: "260px",
      productImageMaxWidth: "100%",
      productImageMaxHeight: "100%",
      productImageAspectRatio: "auto",
      productImageNoPadding: false,
      productImagePadding: "clamp(22px, 2.4vw, 36px)",
      productImageObjectFit: "contain",
      buttonBg: "",
      buttonTextColor: "",
      buttonBorderRadius: "999px",
      buttonBorderWidth: "0px",
      buttonBorderColor: "transparent",
      buttonPaddingY: "11px",
      buttonPaddingX: "18px",
      buttonFontWeight: "720",
      buttonLetterSpacing: "0px",
      buttonHoverBg: "",
      buttonHoverTextColor: "",
      buttonHoverBorderColor: "transparent",
      buttonHoverEffect: "lift",
    },
  },
];
