import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";
import path from "node:path";
import { getBuilderPageBySystemRole, readBuilderCustomPages } from "@/lib/builderLayouts";

const woolberryId = "76f3e619-b66c-4391-90b6-2671fa960132";
const websiteDataPath = (...segments: string[]) =>
  path.join(process.cwd(), "data", "websites", woolberryId, ...segments);

test("Woolberry Shop is a stable assigned Page and commerce archives are routing templates", async () => {
  const pages = await readBuilderCustomPages({ websiteId: woolberryId });
  const shopPage = getBuilderPageBySystemRole(pages, "shop");
  expect(shopPage).toMatchObject({
    id: "wordpress-page:1416",
    key: "page:new-in",
    slug: "new-in",
    systemRole: "shop",
    sourceDatabaseId: 1416,
  });

  const layouts = JSON.parse(await readFile(websiteDataPath("builder-layouts.json"), "utf8"));
  expect(layouts[shopPage!.key]).toBeTruthy();
  expect(layouts.shop).toBeUndefined();
  expect(layouts["product-category"]).toBeTruthy();
  expect(layouts["post-category"]).toBeTruthy();

  const registry = JSON.parse(await readFile(websiteDataPath("builder-routing.json"), "utf8"));
  expect(registry.routingTemplates).toEqual(expect.arrayContaining([
    expect.objectContaining({ view: "archive", layoutId: "layout:builder:product-category" }),
    expect.objectContaining({ view: "archive", layoutId: "layout:builder:post-category" }),
  ]));
});

test("authored commerce layout trees are data-owned rather than generated by a runtime module", async () => {
  await expect(readFile(path.join(process.cwd(), "lib", "commerceBuilderLayouts.ts"), "utf8"))
    .rejects.toMatchObject({ code: "ENOENT" });
  const frontend = await readFile(path.join(process.cwd(), "components", "website", "WebsiteFrontend.tsx"), "utf8");
  expect(frontend).toContain("DefaultShopSurface");
  expect(frontend).toContain("effectiveFallbackContent");
});
