import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";
import path from "node:path";

test("Templates surface is a thin scoped consumer of the routing API", async () => {
  const panel = await readFile(path.join(process.cwd(), "components/dashboard/RoutingTemplatesPanel.tsx"), "utf8");
  const sidebar = await readFile(path.join(process.cwd(), "components/dashboard/DashboardSidebar.tsx"), "utf8");
  const builder = await readFile(path.join(process.cwd(), "components/dashboard/DashboardBuilder.tsx"), "utf8");
  expect(sidebar).toContain('tab: "routingTemplates"');
  expect(sidebar).toContain("<RoutingTemplatesPanel");
  expect(sidebar).toContain("creationContext={templateCreationContext}");
  expect(panel).toContain("/api/routing-templates");
  expect(panel).toContain('action: "create"');
  expect(panel).toContain('action: "reorder"');
  expect(panel).toContain('action: "duplicate"');
  expect(panel).toContain('action: "set-enabled"');
  expect(panel).toContain("initialTemplatePageType");
  expect(panel).toContain("creationContext.previewIdentity");
  expect(panel).toContain("creationContext?.pageType === template.pageType");
  expect(panel).toContain("Open ${displayName(template)} template");
  expect(panel).toContain('aria-label="Edit Template"');
  expect(panel).toContain("editorContext?.ownership.activeTemplate?.templateId");
  expect(panel).toContain("onTemplatesChanged");
  expect(panel).toContain('aria-label="Active template"');
  expect(panel).not.toContain('get("routingTemplate")');
  expect(builder).toContain("refreshRoutingTemplateManagerContext");
  expect(panel).toContain('const [pageType, setPageType] = useState("")');
  expect(panel).not.toContain('useState("singular:product")');
  expect(builder).toContain("editorContext: initialPageHydration!.editorContext");
  expect(panel).toContain("?${params.toString()}");
  expect(panel).toContain("window.location.assign");
  expect(panel).not.toContain("router.push");
  expect(panel).toContain("pageTypes.map");
  expect(panel).toContain("definition.label");
  expect(panel).not.toContain("builder-templates");
  expect(panel).not.toContain("search-results");
});
