import type { BuilderShellSettings } from "@/lib/builderShell";

export type GlobalStyleTokenSource = "global" | "design" | "default";

export type GlobalStyleTokenResolution = {
  value: string;
  source: GlobalStyleTokenSource;
};

/**
 * Canonical appearance-token defaults for the WebPages UIkit foundation.
 * Component renderers may choose semantic defaults, but they must resolve
 * appearance through this table and the generated UIkit variables.
 */
export const GLOBAL_STYLE_TOKEN_DEFAULTS = {
  primaryColor: "#111111",
  accentColor: "#111111",
  secondaryColor: "#64748b",
  mutedColor: "#f1f5f9",
  successColor: "#16a34a",
  warningColor: "#d97706",
  dangerColor: "#dc2626",
  textColor: "#111827",
  backgroundDefault: "#ffffff",
  backgroundMuted: "#f8fafc",
  backgroundPrimary: "#111111",
  backgroundSecondary: "#64748b",
  sectionDefaultColorMode: "light",
  sectionMutedColorMode: "light",
  sectionPrimaryColorMode: "light",
  sectionSecondaryColorMode: "light",
  sectionPaddingXSmall: "20px",
  sectionPaddingSmall: "40px",
  sectionPaddingDefault: "40px",
  sectionPaddingDefaultMedium: "70px",
  sectionPaddingMedium: "80px",
  sectionPaddingLarge: "70px",
  sectionPaddingLargeMedium: "140px",
  sectionPaddingXLarge: "140px",
  sectionPaddingXLargeMedium: "210px",
  backgroundColor: "#ffffff",
  mutedTextColor: "#6b7280",
  emphasisColor: "#111827",
  linkColor: "#111111",
  linkHoverColor: "#111111",
  mutedBackgroundColor: "#f8fafc",
  fontFamilyBody: "system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif",
  fontFamilyHeading: "inherit",
  fontFamilyPrimary: "inherit",
  fontStylePrimary: "inherit",
  fontWeightPrimary: "700",
  letterSpacingPrimary: "inherit",
  textTransformPrimary: "inherit",
  fontFamilySecondary: "inherit",
  fontStyleSecondary: "inherit",
  fontWeightSecondary: "400",
  letterSpacingSecondary: "inherit",
  textTransformSecondary: "inherit",
  fontFamilyTertiary: "inherit",
  fontStyleTertiary: "inherit",
  fontWeightTertiary: "400",
  letterSpacingTertiary: "inherit",
  textTransformTertiary: "inherit",
  baseFontSize: "16px",
  baseLineHeight: "1.5",
  fontSizeSmall: "14px",
  fontSizeMedium: "20px",
  fontSizeLarge: "24px",
  fontSizeXLarge: "34px",
  fontSize2XLarge: "44px",
  inverseColor: "#ffffff",
  headingFontWeight: "700",
  headingSmallFontSize: "30px",
  headingMediumFontSize: "46.2px",
  headingLargeFontSize: "38px",
  headingXLargeFontSize: "44px",
  smallTextFontSize: "14px",
  largeTextFontSize: "24px",
  marginSmall: "15px",
  marginDefault: "30px",
  marginMedium: "40px",
  marginLarge: "70px",
  marginXLarge: "140px",
  gridGutterSmall: "15px",
  gridGutterDefault: "30px",
  gridGutterMedium: "30px",
  gridGutterLarge: "40px",
  containerSmall: "900px",
  containerDefault: "1200px",
  containerLarge: "1400px",
  containerXLarge: "1600px",
  pageContainerMaxWidth: "1600px",
  borderWidth: "1px",
  borderColor: "#e5e7eb",
  borderRadius: "8px",
  shadowSmall: "0 2px 8px rgba(0, 0, 0, 0.06)",
  shadowMedium: "0 8px 24px rgba(0, 0, 0, 0.08)",
  shadowLarge: "0 16px 40px rgba(0, 0, 0, 0.12)",
  shadowXLarge: "0 24px 56px rgba(0, 0, 0, 0.14)",
  cardBackground: "#ffffff",
  cardPrimaryBackground: "#1991ee",
  cardSecondaryBackground: "#0c273a",
  cardBorderRadius: "8px",
  cardBorderWidth: "1px",
  cardBorderColor: "#e5e7eb",
  cardShadow: "0 8px 24px rgba(0, 0, 0, 0.08)",
  cardShadowHover: "0 12px 30px rgba(0, 0, 0, 0.12)",
  cardPaddingSmall: "15px",
  cardPaddingDefault: "30px",
  cardPaddingLarge: "40px",
  navDividerMarginVertical: "0",
  navDefaultFontSize: "14px",
  navDefaultItemColor: "inherit",
  navDefaultItemHoverColor: "inherit",
  navDefaultItemActiveColor: "inherit",
  navDefaultSubtitleFontSize: "12px",
  navDefaultSubtitleColor: "inherit",
  navDefaultSubtitleFontWeight: "inherit",
  navDefaultHeaderColor: "inherit",
  navDefaultSublistItemHoverColor: "inherit",
  navDefaultSublistItemActiveColor: "inherit",
  navDefaultDividerBoxShadow: "none",
  navPrimaryItemColor: "inherit",
  navPrimaryItemHoverColor: "inherit",
  navPrimaryItemActiveColor: "inherit",
  navPrimarySubtitleFontSize: "14px",
  navPrimarySubtitleColor: "inherit",
  navPrimarySubtitleFontWeight: "inherit",
  navPrimaryHeaderColor: "inherit",
  navPrimarySublistItemHoverColor: "inherit",
  navPrimarySublistItemActiveColor: "inherit",
  navPrimaryDividerBoxShadow: "none",
  navSecondaryLineHeight: "1.6",
  navSecondaryItemHoverColor: "inherit",
  navSecondaryItemActiveColor: "inherit",
  navSecondarySubtitleActiveColor: "inherit",
  navSecondarySublistFontSize: "16px",
  navSecondarySublistItemHoverColor: "inherit",
  navSecondarySublistItemActiveColor: "inherit",
  navSecondarySubtitleFontWeight: "inherit",
  navSecondaryMarginTop: "0",
  navSecondaryItemPaddingVertical: "10px",
  navSecondaryItemPaddingHorizontal: "10px",
  navSecondaryItemHoverBackground: "transparent",
  navSecondaryItemActiveBackground: "transparent",
  navSecondaryItemBorderRadius: "0",
  navMediumLineHeight: "1.2",
  navMediumFontSizeResponsive: "62px",
  navDividersMarginTop: "0",
  navDividersBoxShadow: "none",
  inverseNavSecondarySubtitleHoverColor: "inherit",
  inverseNavBackgroundItemHoverBackground: "transparent",
  inverseNavBackgroundItemActiveBackground: "transparent",
  inverseNavSecondaryItemHoverBackground: "transparent",
  inverseNavSecondaryItemActiveBackground: "transparent",
  navbarBackground: "transparent",
  navbarGap: "15px",
  navbarGapMedium: "30px",
  navbarNavGap: "15px",
  navbarNavGapMedium: "30px",
  navbarNavItemHeight: "auto",
  navbarNavItemPaddingHorizontal: "0",
  navbarNavItemPaddingHorizontalMedium: "0",
  navbarNavItemColor: "inherit",
  navbarNavItemHoverColor: "inherit",
  navbarNavItemOnclickColor: "inherit",
  navbarNavItemActiveColor: "inherit",
  navbarNavItemHoverBackground: "transparent",
  navbarNavItemActiveBackground: "transparent",
  navbarNavItemHoverTextShadow: "none",
  navbarNavItemActiveTextShadow: "none",
  navbarNavItemHoverBoxShadow: "none",
  navbarNavItemActiveBoxShadow: "none",
  navbarNavItemFontSize: "16px",
  navbarNavItemTextTransform: "none",
  navbarPrimaryNavItemFontSize: "20px",
  navbarToggleColor: "inherit",
  navbarToggleHoverColor: "inherit",
  navbarSubtitleFontSize: "12px",
  navbarSubtitleColor: "inherit",
  navbarItemPaddingHorizontal: "0",
  navbarItemPaddingHorizontalMedium: "0",
  navbarBackdropFilter: "none",
  navbarMode: "none",
  navbarModeBorderVertical: "none",
  navbarBorderWidth: "0",
  navbarBorder: "transparent",
  navbarNavItemLineMode: "false",
  navbarNavItemLinePositionMode: "bottom",
  navbarNavItemLineSlideMode: "center",
  navbarNavItemLineHeight: "0",
  navbarNavItemLineTransitionDuration: "0.1s",
  navbarNavItemLineHoverHeight: "0",
  navbarNavItemLineOnclickHeight: "0",
  navbarNavItemLineActiveHeight: "0",
  navbarNavItemLineOpacity: "1",
  navbarNavItemLineGradient: "none",
  navbarDropdownIndicator: "none",
  navbarDropdownMargin: "15px",
  navbarDropdownShiftMargin: "0",
  navbarDropdownWidth: "auto",
  navbarDropdownPadding: "25px",
  navbarDropdownBackground: "#ffffff",
  navbarDropdownLargeShiftMargin: "0",
  navbarDropdownDropbarShiftMargin: "0",
  navbarDropdownDropbarPaddingTop: "0",
  navbarDropdownDropbarLargeShiftMargin: "0",
  navbarDropdownNavItemColor: "inherit",
  navbarDropdownNavItemHoverColor: "inherit",
  navbarDropdownNavItemActiveColor: "inherit",
  navbarDropdownNavSubtitleFontSize: "12px",
  navbarDropdownNavSubtitleColor: "inherit",
  navbarDropdownNavSublistItemHoverColor: "inherit",
  navbarDropdownNavSublistItemActiveColor: "inherit",
  navbarDropdownNavItemPaddingVertical: "0",
  navbarDropdownNavFontSize: "14px",
  navbarDropdownBorderRadius: "0",
  navbarDropdownBoxShadow: "none",
  navbarDropdownShiftMarginMedium: "0",
  navbarDropdownDropbarShiftMarginMedium: "0",
  navbarDropdownDropbarLargeShiftMarginMedium: "0",
  inverseNavbarNavItemHoverColor: "inherit",
  imageDefaultRatio: "natural",
  // Matches the canonical BuilderShell default. YOOtheme does not imply a
  // crop mode for a bare Image, so dashboard hydration must not reintroduce
  // the historic Cover default before normalized shell settings arrive.
  imageDefaultFit: "natural",
  imageDefaultLoading: "lazy",
  imageDefaultBorder: "none",
  imageDefaultShadow: "none",
  imageDefaultAlignment: "center",
  sliderArrowStyle: "chevron",
  sliderArrowPosition: "overlay",
  sliderDotnavStyle: "minimal-dots",
  sliderDotnavPosition: "bottom",
  buttonPrimaryBackground: "#111111",
  buttonPrimaryText: "#ffffff",
  buttonDefaultBackground: "#ffffff",
  buttonDefaultText: "#111111",
  buttonSecondaryBackground: "#e5e7eb",
  buttonSecondaryText: "#111111",
  buttonHeight: "44px",
  controlHeightSmall: "40px",
  controlHeightDefault: "48px",
  controlHeightLarge: "56px",
  globalZIndex: "1000",
  breakpointSmall: "640px",
  breakpointMedium: "960px",
  breakpointLarge: "1200px",
  breakpointXLarge: "1600px",
  buttonRadius: "8px",
  buttonBorderWidth: "0px",
  buttonFontSize: "15px",
  // UIkit's 48px default control includes its 2px top/bottom border.
  // The button text line box is therefore 44px.
  buttonLineHeight: "44px",
  buttonFontFamily: "inherit",
  buttonFontStyle: "normal",
  buttonFontWeight: "600",
  buttonTextTransform: "uppercase",
  buttonLetterSpacing: "0px",
  buttonTransitionDuration: "0.2s",
} as const satisfies Record<string, string>;

const DESIGN_ALIASES: Record<string, string[]> = {
  primaryColor: ["primary_color", "primary"],
  accentColor: ["accent_color", "accent"],
  textColor: ["text_color", "text"],
  backgroundColor: ["pageBackground", "page_background", "background"],
  mutedTextColor: ["muted_text_color", "mutedText"],
  mutedBackgroundColor: ["muted_background", "mutedBackground"],
  cardBackground: ["cardBackground", "card_background"],
  cardPrimaryBackground: ["cardPrimaryBackground", "card_primary_background"],
  cardSecondaryBackground: ["cardSecondaryBackground", "card_secondary_background"],
  fontFamilyBody: ["fontFamilyBody", "font_family_body"],
  fontFamilyHeading: ["fontFamilyHeading", "font_family_heading"],
};

function present(value: unknown): value is string | number {
  return value !== undefined && value !== null && String(value).trim() !== "";
}

export function resolveGlobalStyleToken(
  key: string,
  shellSettings?: Partial<BuilderShellSettings>,
  design?: Record<string, unknown>,
  fallback?: string,
): GlobalStyleTokenResolution {
  const shellValue = shellSettings?.[key as keyof BuilderShellSettings];
  if (present(shellValue)) return { value: String(shellValue), source: "global" };

  const aliases = DESIGN_ALIASES[key] ?? [];
  for (const alias of [key, ...aliases]) {
    const designValue = design?.[alias];
    if (present(designValue)) return { value: String(designValue), source: "design" };
  }

  const defaultValue = GLOBAL_STYLE_TOKEN_DEFAULTS[key as keyof typeof GLOBAL_STYLE_TOKEN_DEFAULTS];
  return { value: defaultValue ?? fallback ?? "", source: "default" };
}

export function resolveAppearanceValue<T>(options: {
  global?: T;
  componentDefault: T;
  local?: T;
}): { value: T; source: "global" | "component-default" | "local" } {
  if (options.local !== undefined) return { value: options.local, source: "local" };
  if (options.global !== undefined) return { value: options.global, source: "global" };
  return { value: options.componentDefault, source: "component-default" };
}
